### ISSUE TITLE
Possible changes for v0.14.x

### ISSUE THREAD

**Issue by purefunctor** [csicar/purescript-typelevel-peano#3]
Hello, I'm currently writing [typelevel-lists](https://github.com/PureFunctor/purescript-typelevel-lists) which utilizes this package for the length, take, and drop utilities. So far, I've gotten this package to compile on `v0.14.0-rc5` with minimal warnings, although with a few API changes, namely the removal of `IProxy` and `NProxy` in favor of `Proxy`; you can check it out [in my fork](https://github.com/PureFunctor/purescript-typelevel-peano/tree/next). Just thought I'd ask through an issue first to discuss the possible changes that would have to be implemented in the future, many thanks.

**Comment by csicar** [comment]
That's awesome! 

I think those API changes do make sense and need to be carried out. So feel free to create a PR!

**Comment by csicar** [comment]
I'll also replace `unsafeCoerce unit :: Proxy ..` with `Proxy :: Proxy ...` .
Not sure why I though that was a good idea.

**Comment by purefunctor** [comment]
Thanks! Anyhow, I'll make the PR once v0.14.0 officially releases along with the package sets.

**Comment by csicar** [comment]
Feel free to create the PR right away (You can mark it as "WIP: " if you feel more comfortable with that). That way we can work out any changes to your PR before 0.14 is released

**Comment by csicar** [comment]
I published a new version: `1.0.1` https://pursuit.purescript.org/packages/purescript-typelevel-peano/1.0.1, which includes your contributions
